spring.application.name=CBB-BACKEND

spring.datasource.url=jdbc:mysql://localhost:3306/corebank_bridge
spring.datasource.username=root
spring.datasource.password=Darshu@322

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

